#! zsh

# startup script order:
#       /etc/zshenv                     (always)
#       $ZDOTDIR/.zshenv    RCS
#       /etc/zprofile       GLOBAL_RCS   login
#       $ZDOTDIR/.zprofile  RCS          login
#       /etc/zshrc          GLOBAL_RCS   interactive
#       $ZDOTDIR/.zshrc     RCS          interactive
#       /etc/zlogin         GLOBAL_RCS   login
#       $ZDOTDIR/.zlogin    RCS          login 
# exit script order:
#       $ZDOTDIR/.zlogout   RCS          login
#       /etc/zlogout        GLOBAL_RCS   login
# Note any of these files can be compiled using `zcompile`. Name appended
# with .zwc (e.g. .zshlogin.zwc, I suppose)

# run Zsh configuration questionnaire:
#       `autoload -U zsh-newuser-install && zsh-newuser-install -f`
# completions configuration questionnaire:
#       `autoload -Uz compinstall && compinstall`

fpath=($ZDOTDIR/functions $fpath)

autoload -Uz add-zsh-hook  # && add-zsh-hook (not required; dunno why not)

# === Asynchronous Zsh =================================================
# https://github.com/mafredri/zsh-async
#source $ZDOTDIR/opt/zsh-async/async.zsh
autoload -Uz async && async

# === Deferred Zsh =====================================================
# https://github.com/romkatv/zsh-defer
source $ZDOTDIR/opt/zsh-defer/zsh-defer.plugin.zsh

# === Functional Zsh ===================================================
# https://github.com/Tarrasch/zsh-functional
source $ZDOTDIR/opt/zsh-functional/functional.plugin.zsh

# === basic configuration ==============================================
source $ZDOTDIR/startup/basic.zsh
source $ZDOTDIR/startup/identify-machine.zsh
source $ZDOTDIR/startup/path.zsh

# color
if type dircolors > /dev/null 2>&1 ; then
    [[ -r ~/.bash/dircolors ]] && eval "$(dircolors -b ~/.bash/dircolors)" || eval "$(dircolors -b)"
fi

# I like using # in interactive shells
setopt INTERACTIVE_COMMENTS
setopt KSH_GLOB  # zshexpn(1)
setopt EXTENDED_GLOB  # zshexpn(1)

# history
HISTFILE=~/.zsh/history
HISTSIZE=10000
SAVEHIST=100000
setopt HIST_FCNTL_LOCK
setopt HIST_IGNORE_DUPS
setopt EXTENDED_HISTORY
# still unsure whether I want this or just APPEND_HISTORY
setopt INC_APPEND_HISTORY_TIME

# So ^D won't kill a terminal window
setopt IGNORE_EOF

#zstyle :completion::complete:git-checkout:argument-rest:headrefs command "git for-each-ref --format='%(refname)' refs/heads 2>/dev/null"

# === Homebrew =========================================================
if [[ -x /opt/homebrew/bin/brew ]]; then
    export HOMEBREW_CASK_OPTS="--appdir=$HOME/Applications"
    export HOMEBREW_NO_ENV_HINTS=1
    export HOMEBREW_EVAL_ALL=1
    eval "$(/opt/homebrew/bin/brew shellenv)"
fi

# === this is for building DosBox Staging ==============================
if [[ -d $HOME/src/vcpkg ]]; then
    export VCPKG_ROOT=$HOME/src/vcpkg
fi

# === Raku =============================================================
export RAKUBREW_HOME="$HOME/.raku/rakubrew"
if [[ -x $HOME/.raku/rakubrew/bin/rakubrew ]]; then
    eval "$($HOME/.raku/rakubrew/bin/rakubrew init Zsh)"
fi

# === Perl =============================================================
ptolemarch_perl5_root="$HOME/.perl5"
export PLENV_ROOT="$ptolemarch_perl5_root/plenv"
# documenting this here because not sure where else
# plenv install 5.36.0 --test -j 8 -Doptimize=-O3 -Dlocincpth=/usr/local/include -Dloclibpth=/usr/local/lib
# plenv install 5.32.0 --as=teapot --test -j 8 -Doptimize=-O3 -Dlocincpth=/usr/local/include -Dloclibpth=/usr/local/lib
#
# chromebook:
# plenv install 5.40.0 --as=teapot --test -j 4 -Doptimize='-O3 -march=native' -Dusequadmath -Dlocincpth=/usr/local/include -Dloclibpth=/usr/local/lib

if [[ -d $ptolemarch_perl5_root/minicpan ]]; then
    ptolemarch_cpanm_cpan_mirror="file://$ptolemarch_perl5_root/minicpan/"
    export PERL_CPANM_OPT="--mirror $ptolemarch_cpanm_cpan_mirror --mirror-only"
fi
export PERL_CPANM_HOME="$ptolemarch_perl5_root/cpanm"

if ! [[ -n $PLENV_INIT_ALREADY ]]; then
    export PLENV_INIT_ALREADY=1
    # initialize plenv, but only if we're NOT on perceptyx jail
    #  (which uses perlbrew)
    eval "$(plenv init - zsh)"
fi

# === Go ===============================================================
#GOPATH="$HOME/.go"
#
#export GOPATH

# === Python ===========================================================
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
#__conda_setup="$('/Users/davidhand/.python/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
#if [ $? -eq 0 ]; then
#    eval "$__conda_setup"
#else
#    if [ -f "/Users/davidhand/.python/miniconda3/etc/profile.d/conda.sh" ]; then
#        . "/Users/davidhand/.python/miniconda3/etc/profile.d/conda.sh"
#    else
#        export PATH="/Users/davidhand/.python/miniconda3/bin:$PATH"
#    fi
#fi
#unset __conda_setup
# <<< conda initialize <<<

ptolemarch_python_venv="$HOME/.python/venv"
ptolemarch_python_venv_activate="$ptolemarch_python_venv/bin/activate"
if [ -f "$ptolemarch_python_venv_activate" ]; then
    export VIRTUAL_ENV_DISABLE_PROMPT=1
    source "$ptolemarch_python_venv_activate"
fi

# == rlwrap (readline command wrapper) =================================
export RLWRAP_HOME="$HOME/.rlwrap"

# === iTerm2 ===========================================================
#ITERM2_SI_PATH=$ZDOTDIR/startup/iterm2_shell_integration.zsh
#test -f $ITERM2_SI_PATH && source $ITERM2_SI_PATH;

# === Zsh Help =========================================================
unalias run-help 2> /dev/null
#HELPDIR=/usr/share/zsh/5.9/help/  # this line doesn't appear to be necessary
autoload run-help
alias help=run-help

# === Zsh Completions ==================================================
# https://github.com/zsh-users/zsh-completions
fpath=($ZDOTDIR/opt/zsh-completions/src $fpath)
autoload -U compinit && compinit
#zstyle ':completion::complete:*' use-cache 1
# will the above still use Gentoo's app-shells/gentoo-zsh-completions ?


## == compinstall did this ==============================================
## The following lines were added by compinstall
#
#zstyle ':completion:*' auto-description 'specify: %d'
#zstyle ':completion:*' completer _oldlist _expand _complete _ignored _match _prefix
#zstyle ':completion:*' completions 1
#zstyle ':completion:*' format 'completing %d'
#zstyle ':completion:*' glob 1
#zstyle ':completion:*' group-name ''
#zstyle ':completion:*' insert-unambiguous true
#zstyle ':completion:*' list-colors ''
#zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
#zstyle ':completion:*' match-original both
#zstyle ':completion:*' matcher-list '+' '+r:|[._-]=* r:|=*'
#zstyle ':completion:*' max-errors 2 numeric
#zstyle ':completion:*' menu select=2
#zstyle ':completion:*' original true
#zstyle ':completion:*' prompt 'correcting %e>'
#zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
#zstyle ':completion:*' substitute 1
#zstyle :compinstall filename '/Users/davidhand/.zshrc'
#
#autoload -Uz compinit && compinit
## -- end compinstall ---------------------------------------------------
## == zsh-newuser-install ===============================================
#setopt AUTO_CD BEEP EXTENDED_GLOB NOMATCH
#bindkey -v
## -- end zsh-newuser-install -------------------------------------------
#
## use completion system to handle expansion. Works with the _expand completer,
##  above. See zshcompsys(1)
## (by default, '^I' is bound to expand-or-complete)
#bindkey '^I' complete-word
## allow shift-tab to be used to go backwards in a completion menu
#bindkey '^[[Z' reverse-menu-complete
#
## allow zsh to correct command names
#setopt CORRECT
## but stop suggesting the autocompletion functions for missing commands
#CORRECT_IGNORE='_*'
## there's also a CORRECT_IGNORE_FILE parameter that does something similar

# === Zsh Autosuggestions ==============================================
# https://github.com/zsh-users/zsh-autosuggestions
zsh-defer source $ZDOTDIR/opt/zsh-autosuggestions/zsh-autosuggestions.zsh

# === Command-Not-Found ================================================
[[ -r /etc/zsh_command_not_found ]] \
&& zsh-defer source /etc/zsh_command_not_found 

# === Zsh Aliases ======================================================
zsh-defer source $ZDOTDIR/startup/aliases.zsh

# === Zsh Prompt =======================================================
zsh-defer source $ZDOTDIR/startup/prompt.zsh

# === Zsh Vi Mode ======================================================
# https://github.com/jeffreytse/zsh-vi-mode
# if this begins to get annoying, look at
# https://stratus3d.com/blog/2017/10/26/better-vi-mode-in-zshell/
function zvm_config() {
    ZVM_KEYTIMEOUT=0.1
    ZVM_ESCAPE_KEYTIMEOUT=0
    ZVM_LINE_INIT_MODE=$ZVM_MODE_INSERT
}
zsh-defer source $ZDOTDIR/opt/zsh-vi-mode/zsh-vi-mode.plugin.zsh
function zvm_after_init() {
}
function zvm_after_lazy_keybindings_commands() {
    # put any extra bindkey stuff here
    # also presumably any plugins that provide their own key bindings
    # (e.g. fzf)
}

# === Zsh Syntax Highlighting ==========================================
# https://github.com/zsh-users/zsh-syntax-highlighting
# Apparently, this needs to be at the end?
zsh-defer source $ZDOTDIR/opt/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# vim: ts=4 sw=4 et ai
