["bin"]
	url = "https://github.com/ptolemarch/bin.git"
	type = "git-repo"
	refreshPeriod = "24h"  # one day
["Code/Hesitations"]
	url = "https://github.com/ptolemarch/hesitations.git"
	type = "git-repo"
	refreshPeriod = "24h"  # one day

[".perl5/plenv"]
	url = "https://github.com/tokuhirom/plenv.git"
	type = "git-repo"
	refreshPeriod = "672h"  # four weeks

[".zsh/opt/printc-"]
	url = "https://github.com/philFernandez/printc-.git"
	type = "git-repo"
	refreshPeriod = "672h"  # four weeks
[".zsh/opt/zsh-async"]
	url = "https://github.com/mafredri/zsh-async.git"
	type = "git-repo"
	refreshPeriod = "672h"  # four weeks
[".zsh/opt/zsh-functional"]
	url = "https://github.com/ptolemarch/zsh-functional.git"
	type = "git-repo"
	refreshPeriod = "672h"  # four weeks

[".vim/pack/plugins/start/vim-go"]
	url = "https://github.com/fatih/vim-go.git"
	type = "git-repo"
	refreshPeriod = "672h"  # four weeks
[".vim/bundle/mojo.vim"]
	url = "https://github.com/yko/mojo.vim.git"
	type = "git-repo"
	refreshPeriod = "672h"  # four weeks
[".vim/bundle/vim-pathogen"]
	url = "https://github.com/tpope/vim-pathogen.git"
	type = "git-repo"
	refreshPeriod = "672h"  # four weeks
[".vim/bundle/vim-perl"]
	url = "https://github.com/vim-perl/vim-perl.git"
	type = "git-repo"
	refreshPeriod = "672h"  # four weeks
[".vim/bundle/vim-perl6"]
	url = "https://github.com/vim-perl/vim-perl6.git"
	type = "git-repo"
	refreshPeriod = "672h"  # four weeks
[".vim/bundle/vim-systemd-syntax"]
	url = "https://github.com/wgwoods/vim-systemd-syntax.git"
	type = "git-repo"
	refreshPeriod = "672h"  # four weeks
[".vim/bundle/haskell-vim"]
	url = "https://github.com/neovimhaskell/haskell-vim.git"
	type = "git-repo"
	refreshPeriod = "672h"  # four weeks
[".vim/bundle/html5.vim"]
	url = "https://github.com/othree/html5.vim.git"
	type = "git-repo"
	refreshPeriod = "672h"  # four weeks
[".vim/bundle/vim-javascript"]
	url = "https://github.com/pangloss/vim-javascript.git"
	type = "git-repo"
	refreshPeriod = "672h"  # four weeks
[".vim/bundle/ack.vim"]
	url = "https://github.com/mileszs/ack.vim.git"
	type = "git-repo"
	refreshPeriod = "672h"  # four weeks
[".vim/bundle/jq.vim"]
	url = "https://github.com/vito-c/jq.vim.git"
	type = "git-repo"
	refreshPeriod = "672h"  # four weeks
