# vim: ts=8 sw=8 noet ai

# Note: This file is interpreted as a template, whether or not it has
#   a .tmpl extension. See
#     https://www.chezmoi.io/reference/special-files/chezmoiexternal-format/

# My Own Repos
["bin"]
	type = "git-repo"
	url = "https://github.com/ptolemarch/bin.git"
	refreshPeriod = "24h"  # one day
["Code/Hesitations"]
	type = "git-repo"
	url = "https://github.com/ptolemarch/Hesitations.git"
	refreshPeriod = "24h"  # one day

# Fonts
# *** TODO: .fonts/IosevkaPtolemarchTerm/***
[".fonts/JuliaMono"]
	type = "archive"
	url = "https://github.com/cormullion/juliamono/releases/download/v0.059/JuliaMono-ttf.zip"
	refreshPeriod = "0"  # never; version-specific URL
[".fonts/clacon2.ttf"]
	type = "file"
	url = "https://webdraft.hu/fonts/classic-console/fonts/clacon2.ttf"
	refreshPeriod = "672h"  # four weeks
[".fonts/Ultima_4_polished_runes.ttf"]
	type = "archive-file"
	url = "https://ultimacodex.com/foundation/Ultima_4_polished_runes.zip"
	path = "Ultima_4_polished_runes.ttf"
	refreshPeriod = "4383h"  # six months
[".fonts/Ultima_5_polished_runes.ttf"]
	type = "archive-file"
	url = "https://ultimacodex.com/foundation/Ultima_5_polished_runes.zip"
	path = "Ultima_5_polished_runes.ttf"
	refreshPeriod = "4383h"  # six months
[".fonts/Catrinity.otf"]
	type = "file"
	url = "https://catrinity-font.de/downloads/Catrinity.otf"
	refreshPeriod = "672h"  # four weeks
[".fonts/CatrinityFlags.otf"]
	type = "file"
	url = "https://catrinity-font.de/downloads/CatrinityFlags.otf"
	refreshPeriod = "672h"  # four weeks
[".fonts/devicon.ttf"]
	type = "archive-file"
	url = "https://github.com/devicons/devicon/archive/master.zip"
	stripComponents = 2
	path = "devicon.ttf"
	refreshPeriod = "4383h"  # six months
[".fonts/Unicode_IEC_symbol.ttf"]
	type = "file"
	url = "https://unicodepowersymbol.com/wp-content/uploads/2015/05/Unicode_IEC_symbol.ttf"
	refreshPeriod = "0"  # never; seems like a single release
[".fonts/fontawesome"]
	type = "archive"
	url = "https://github.com/FortAwesome/Font-Awesome/releases/download/6.7.2/fontawesome-free-6.7.2-desktop.zip"
	stripComponents = 2
	include = [ "*/otfs/**" ]
	refreshPeriod = "0"  # never; version-specific URL
[".fonts/font-awesome-extension.ttf"]
	type = "archive-file"
	url = "https://github.com/AndreLGava/font-awesome-extension/archive/v.0.0.3.tar.gz"
	stripComponents = 2
	path = "font-awesome-extension.ttf"
	refreshPeriod = "0"  # never; apparently semi-abandoned
[".fonts/MaterialDesignIconsDesktop.ttf"]
	type = "file"
	url = "https://github.com/Templarian/MaterialDesign-Font/raw/refs/heads/master/MaterialDesignIconsDesktop.ttf"
	refreshPeriod = "0"  # never; apparently semi-abandoned
[".fonts/MaterialDesignIconsDesktop-cheatsheet.html"]
	type = "file"
	url = "https://raw.githubusercontent.com/Templarian/MaterialDesign-Font/refs/heads/master/cheatsheet.html"
	refreshPeriod = "0"  # never; apparently semi-abandoned
[".fonts/MaterialDings.ttf"]
	type = "file"
	url = "https://github.com/Pictogrammers/MaterialDings/raw/refs/heads/main/dist/fonts/MaterialDings.ttf"
	refreshPeriod = "0"  # never; apparently semi-abandoned
[".fonts/font-logos.ttf"]
	type = "archive-file"
	url = "https://github.com/lukas-w/font-logos/releases/download/v1.3.0/font-logos-1.3.0.zip"
	stripComponents = 2
	path = "font-logos.ttf"
	refreshPeriod = "0"  # never; version-specific URL
[".fonts/font-mfizz.ttf"]
	type = "file"
	url = "https://github.com/fizzed/font-mfizz/raw/refs/heads/master/dist/font-mfizz.ttf"
	refreshPeriod = "0"  # never; apparently semi-abandoned
[".fonts/codicon.ttf"]
	type = "file"
	url = "https://github.com/microsoft/vscode-codicons/releases/download/0.0.36/codicon.ttf"
	refreshPeriod = "0"  # never; apparently semi-abandoned
[".fonts/weathericons-regular-webfont.ttf"]
	type = "archive-file"
	url = "https://github.com/erikflowers/weather-icons/archive/master.zip"
	stripComponents = 2
	path = "weathericons-regular-webfont.ttf"
	refreshPeriod = "0"  # never


# plenv and its plugins
[".perl5/plenv"]
	type = "git-repo"
	url = "https://github.com/tokuhirom/plenv.git"
	refreshPeriod = "672h"  # four weeks
[".perl5/plenv/plugins/plenv-libdirs"]
	type = "git-repo"
	url = "https://github.com/mikkoi/plenv-libdirs.git"
	refreshPeriod = "672h"  # four weeks
[".perl5/plenv/plugins/perl-build"]
	type = "git-repo"
	url = "https://github.com/tokuhirom/Perl-Build.git"
	refreshPeriod = "672h"  # four weeks
[".perl5/plenv/plugins/plenv-contrib"]
	type = "git-repo"
	url = "https://github.com/miyagawa/plenv-contrib.git"
	refreshPeriod = "672h"  # four weeks

# Zsh Plugins: from zsh-users
[".zsh/opt/zsh-completions"]
	type = "git-repo"
	url = "https://github.com/zsh-users/zsh-completions"
	refreshPeriod = "672h"  # four weeks
[".zsh/opt/zsh-autosuggestions"]
	type = "git-repo"
	url = "https://github.com/zsh-users/zsh-autosuggestions"
	refreshPeriod = "672h"  # four weeks
[".zsh/opt/zsh-syntax-highlighting"]
	type = "git-repo"
	url = "https://github.com/zsh-users/zsh-syntax-highlighting"
	refreshPeriod = "672h"  # four weeks
[".zsh/opt/zsh-history-substring-search"]
	type = "git-repo"
	url = "https://github.com/zsh-users/zsh-history-substring-search"
	refreshPeriod = "672h"  # four weeks

# Zsh Plugins: others
[".zsh/opt/printc-"]
	type = "git-repo"
	url = "https://github.com/philFernandez/printc-.git"
	refreshPeriod = "672h"  # four weeks
[".zsh/opt/zsh-async"]
	type = "git-repo"
	url = "https://github.com/mafredri/zsh-async.git"
	refreshPeriod = "672h"  # four weeks
[".zsh/opt/zsh-defer"]
	type = "git-repo"
	url = "https://github.com/romkatv/zsh-defer.git"
	refreshPeriod = "672h"  # four weeks
[".zsh/opt/zsh-functional"]
	type = "git-repo"
	url = "https://github.com/ptolemarch/zsh-functional.git"
	refreshPeriod = "672h"  # four weeks
[".zsh/opt/zsh-vi-mode"]
	type = "git-repo"
	url = "https://github.com/jeffreytse/zsh-vi-mode.git"
	refreshPeriod = "672h"  # four weeks

# Vim Plugins
[".vim/pack/plugins/start/vim-go"]
	type = "git-repo"
	url = "https://github.com/fatih/vim-go.git"
	refreshPeriod = "672h"  # four weeks
[".vim/bundle/mojo.vim"]
	type = "git-repo"
	url = "https://github.com/yko/mojo.vim.git"
	refreshPeriod = "672h"  # four weeks
[".vim/bundle/vim-pathogen"]
	type = "git-repo"
	url = "https://github.com/tpope/vim-pathogen.git"
	refreshPeriod = "672h"  # four weeks
[".vim/bundle/vim-perl"]
	type = "git-repo"
	url = "https://github.com/vim-perl/vim-perl.git"
	refreshPeriod = "672h"  # four weeks
[".vim/bundle/vim-perl6"]
	type = "git-repo"
	url = "https://github.com/vim-perl/vim-perl6.git"
	refreshPeriod = "672h"  # four weeks
[".vim/bundle/vim-systemd-syntax"]
	type = "git-repo"
	url = "https://github.com/wgwoods/vim-systemd-syntax.git"
	refreshPeriod = "672h"  # four weeks
[".vim/bundle/haskell-vim"]
	type = "git-repo"
	url = "https://github.com/neovimhaskell/haskell-vim.git"
	refreshPeriod = "672h"  # four weeks
[".vim/bundle/html5.vim"]
	type = "git-repo"
	url = "https://github.com/othree/html5.vim.git"
	refreshPeriod = "672h"  # four weeks
[".vim/bundle/vim-javascript"]
	type = "git-repo"
	url = "https://github.com/pangloss/vim-javascript.git"
	refreshPeriod = "672h"  # four weeks
[".vim/bundle/ack.vim"]
	type = "git-repo"
	url = "https://github.com/mileszs/ack.vim.git"
	refreshPeriod = "672h"  # four weeks
[".vim/bundle/jq.vim"]
	type = "git-repo"
	url = "https://github.com/vito-c/jq.vim.git"
	refreshPeriod = "672h"  # four weeks
