# My Own Repos
["bin"]
	type = "git-repo"
	url = "https://github.com/ptolemarch/bin.git"
	refreshPeriod = "24h"  # one day
["Code/Hesitations"]
	type = "git-repo"
	url = "https://github.com/ptolemarch/Hesitations.git"
	refreshPeriod = "24h"  # one day

# Fonts
[".fonts/Catrinity.otf"]
	type = "file"
	url = "https://catrinity-font.de/downloads/Catrinity.otf"
	refreshPeriod = "672h"  # four weeks
[".fonts/CatrinityFlags.otf"]
	type = "file"
	url = "https://catrinity-font.de/downloads/CatrinityFlags.otf"
	refreshPeriod = "672h"  # four weeks

# plenv and its plugins
[".perl5/plenv"]
	type = "git-repo"
	url = "https://github.com/tokuhirom/plenv.git"
	refreshPeriod = "672h"  # four weeks
[".perl5/plenv/plugins/plenv-libdirs"]
	type = "git-repo"
	url = "https://github.com/mikkoi/plenv-libdirs.git"
	refreshPeriod = "672h"  # four weeks
[".perl5/plenv/plugins/perl-build"]
	type = "git-repo"
	url = "https://github.com/tokuhirom/Perl-Build.git"
	refreshPeriod = "672h"  # four weeks
[".perl5/plenv/plugins/plenv-contrib"]
	type = "git-repo"
	url = "https://github.com/miyagawa/plenv-contrib.git"
	refreshPeriod = "672h"  # four weeks

# Zsh Plugins: from zsh-users
[".zsh/opt/zsh-completions"]
	type = "git-repo"
	url = "https://github.com/zsh-users/zsh-completions"
	refreshPeriod = "672h"  # four weeks
[".zsh/opt/zsh-autosuggestions"]
	type = "git-repo"
	url = "https://github.com/zsh-users/zsh-autosuggestions"
	refreshPeriod = "672h"  # four weeks
[".zsh/opt/zsh-syntax-highlighting"]
	type = "git-repo"
	url = "https://github.com/zsh-users/zsh-syntax-highlighting"
	refreshPeriod = "672h"  # four weeks
[".zsh/opt/zsh-history-substring-search"]
	type = "git-repo"
	url = "https://github.com/zsh-users/zsh-history-substring-search"
	refreshPeriod = "672h"  # four weeks

# Zsh Plugins: others
[".zsh/opt/printc-"]
	type = "git-repo"
	url = "https://github.com/philFernandez/printc-.git"
	refreshPeriod = "672h"  # four weeks
[".zsh/opt/zsh-async"]
	type = "git-repo"
	url = "https://github.com/mafredri/zsh-async.git"
	refreshPeriod = "672h"  # four weeks
[".zsh/opt/zsh-defer"]
	type = "git-repo"
	url = "https://github.com/romkatv/zsh-defer.git"
	refreshPeriod = "672h"  # four weeks
[".zsh/opt/zsh-functional"]
	type = "git-repo"
	url = "https://github.com/ptolemarch/zsh-functional.git"
	refreshPeriod = "672h"  # four weeks

# Vim Plugins
[".vim/pack/plugins/start/vim-go"]
	type = "git-repo"
	url = "https://github.com/fatih/vim-go.git"
	refreshPeriod = "672h"  # four weeks
[".vim/bundle/mojo.vim"]
	type = "git-repo"
	url = "https://github.com/yko/mojo.vim.git"
	refreshPeriod = "672h"  # four weeks
[".vim/bundle/vim-pathogen"]
	type = "git-repo"
	url = "https://github.com/tpope/vim-pathogen.git"
	refreshPeriod = "672h"  # four weeks
[".vim/bundle/vim-perl"]
	type = "git-repo"
	url = "https://github.com/vim-perl/vim-perl.git"
	refreshPeriod = "672h"  # four weeks
[".vim/bundle/vim-perl6"]
	type = "git-repo"
	url = "https://github.com/vim-perl/vim-perl6.git"
	refreshPeriod = "672h"  # four weeks
[".vim/bundle/vim-systemd-syntax"]
	type = "git-repo"
	url = "https://github.com/wgwoods/vim-systemd-syntax.git"
	refreshPeriod = "672h"  # four weeks
[".vim/bundle/haskell-vim"]
	type = "git-repo"
	url = "https://github.com/neovimhaskell/haskell-vim.git"
	refreshPeriod = "672h"  # four weeks
[".vim/bundle/html5.vim"]
	type = "git-repo"
	url = "https://github.com/othree/html5.vim.git"
	refreshPeriod = "672h"  # four weeks
[".vim/bundle/vim-javascript"]
	type = "git-repo"
	url = "https://github.com/pangloss/vim-javascript.git"
	refreshPeriod = "672h"  # four weeks
[".vim/bundle/ack.vim"]
	type = "git-repo"
	url = "https://github.com/mileszs/ack.vim.git"
	refreshPeriod = "672h"  # four weeks
[".vim/bundle/jq.vim"]
	type = "git-repo"
	url = "https://github.com/vito-c/jq.vim.git"
	refreshPeriod = "672h"  # four weeks
