#!/bin/sh

# == redirect output to files ==========================================
stdout="$HOME/.X11.out" 
stderr="$HOME/.X11.err" 

for std in "$stdout" "$stderr" ; do
	[[ -f "$std" ]] && mv -f "$std" "$std.prev"
done
exec > "$stdout" 2> "$stderr"

# == load preferences and key modifications ============================
userresources="$HOME/.Xresources"
usermodmap="$HOME/.Xmodmap"
sysresources=/etc/X11/xinit/Xresources
sysmodmap=/etc/X11/xinit/Xmodmap

# in /etc/X11/xinit/xinitrc, they actually do
# - sysresources
# - sysmodmap
# - userresources
# - usermodmap
# but, as you can see, I'm doing the resources first, then the modmaps.
# Hopefully that won't break anything.
for resources in "$sysresources" "$userresources" ; do
	includes="$( dirname "$resources" )"
	[[ -f "$resources" ]] && xrdb -merge -I"$includes" "$resources"
done
for modmap in "$sysmodmap" "$usermodmap" ; do
	[[ -f "$modmap" ]] && xmodmap "$modmap"
done

# == arrange displays ==================================================
# desk at home: two large external monitors, both to the left
xrandr \
	--output   DP-0 --primary \
	--output   DP-1  --left-of DP-0 \
	--output   DP-3  --left-of DP-1 #\
#	--output HDMI-0 --right-of DP-0 --rotate right

# on the move: portable external monitor on the left
#xrandr \
#	--output DP-0   --auto --primary     --pos 1080x0 \
#	--output HDMI-0 --auto --rotate left --pos 0x120

#picom --backend glx --dbus --daemon 

# == set default mouse pointer and background ==========================
xsetroot \
	-xcf ~/.config/Ptolemarch/hand 32 \
	-bitmap ~/.config/Ptolemarch/houndstoothProperSizeProperWidth.xbm \
	-fg dodgerblue4 \
	-bg gray6

# == start things up ===================================================
# straight from http://www.incenp.org/notes/2014/gnupg-for-ssh-authentication.html
#if test -f $XDG_RUNTIME_DIR/gpg-agent-info && kill -0 $(head -n 1 $XDG_RUNTIME_DIR/gpg-agent-info | cut -d: -f2) 2>/dev/null ; then
#    eval $(< $XDG_RUNTIME_DIR/gpg-agent-info)
#else
#    eval $(gpg-agent --daemon --enable-ssh-support --write-env-file $XDG_RUNTIME_DIR/gpg-agent-info)
#fi
#export GPG_AGENT_INFO
#export SSH_AUTH_SOCK

# wanna set up dbus explicitly
# xmobar
# mpd ?
# ssh agent for whole session (not just per-terminal)
# better notifications
#  - hexchat notifications?

# start things up
#eval $(ssh-agent -s)
xscreensaver -no-splash &

/usr/bin/xmonad

# == shut things down ==================================================
#ssh-agent -k
xscreensaver-command -exit
